[build]
  publish = "."

[[headers]]
  for = "/go/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    Cache-Control = "no-store, max-age=0"

[[redirects]]
  from = "/go/facebook"
  to = "https://m.facebook.com/hisnaman1"
  status = 302
  force = true

[[redirects]]
  from = "/go/instagram"
  to = "https://www.instagram.com/_u/hisn_aman/"
  status = 302
  force = true

[[redirects]]
  from = "/go/tiktok"
  to = "https://www.tiktok.com/@hisn.aman"
  status = 302
  force = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
