[build]
  publish = "."

[[headers]]
  for = "/go/*"
  [headers.values]
    Referrer-Policy = "no-referrer"
    Cache-Control = "no-store, max-age=0"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
